-- SQLBook: Code
BEGIN;

DROP TABLE IF EXISTS "user", "game", "collection";

CREATE TABLE "user"(
    "id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "email" VARCHAR NOT NULL,
    "nickname" VARCHAR NOT NULL,
    "password" VARCHAR NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE "game"(
    "id" INT PRIMARY KEY NOT NULL
);

CREATE TABLE "collection"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "user" ("id"),
    "game_id" INT NOT NULL REFERENCES "game" ("id")
);


COMMIT;