

CREATE OR REPLACE FUNCTION public.insert_game(
    api_id_value integer,
    slug_value character varying)
RETURNS integer
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    game_id integer;  -- Declare a variable to store the game ID (generated by default by pg).
BEGIN
    -- Try to insert a new record into the "game" table.
    -- If there is a conflict with an existing "api_id," we do nothing.
    -- If successful, return the newly generated "id" into the "game_id" variable.
    INSERT INTO "game"("api_id", "slug") VALUES (api_id_value, slug_value)
    ON CONFLICT (api_id) DO NOTHING
    RETURNING "id" INTO game_id;

    -- If the insert was successful (game_id is not NULL), return the game_id.
    IF game_id IS NOT NULL THEN
        RETURN game_id;
    END IF;

    -- If the insert failed due to a conflict, retrieve the existing "id" for the given "api_id."
    SELECT "id" INTO game_id FROM "game" WHERE "api_id" = api_id_value;
    RETURN game_id;  -- Return the game_id.
END;
$BODY$;

-- Change the owner of the function to "retrogame."
ALTER FUNCTION public.insert_game(integer, character varying)
    OWNER TO retrogame;
